name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00 UTC
  workflow_dispatch: # Allow manual trigger
  - name: Set Git user
run: |
      git config --global user.name "github-actions[bot]"
      git.config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          date >> daily.txt # Append current date
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily commit"
